### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/javamail#335]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by m0mus** [comment]
I already answered here: https://github.com/eclipse-ee4j/javamail/issues/336

@bshannon. are you ok if @scottmarlow will help with this task.

**Comment by bshannon** [comment]
Build job created:
https://jenkins.eclipse.org/javamail/job/javamail-branch-build/

Currently it skips unit tests because of some JDK or Docker or Linux problem that causes tests to fail.
