### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/javamail#336]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by scottmarlow** [comment]
Hi, I'd like to volunteer to help with this as well.

**Comment by scottmarlow** [comment]
@eclipsewebmaster could you please help me link my http://github.com/scottmarlow/ account to my https://accounts.eclipse.org/users/smarlowsxi account, so I can assign this issue to myself?  Thanks!

**Comment by m0mus** [comment]
@scottmarlow You are not a committer to this project (yet). Only committers can be assigned to issues. You can still work on this issue the way we discussed on the meeting today. Submit your PR, committers will review and merge it after the review is successful.
I am also asking @bshannon, who is the project lead. Bill do you agree if @scottmarlow will help with this task.

**Comment by scottmarlow** [comment]
FYI, I started making changes on https://github.com/scottmarlow/javamail/tree/EE4J_8_hacking.  I'll create an initial pr from that.

**Comment by m0mus** [comment]
@scottmarlow thank you!

**Comment by bshannon** [comment]
Release jobs created:
https://jenkins.eclipse.org/javamail/job/javamail-branch-build-release/
https://jenkins.eclipse.org/javamail/job/javamail-branch-release-final/
