### ISSUE TITLE
draft mail does not have draft flag set for Gmail

### ISSUE THREAD

**Issue by m00nlight** [eclipse-ee4j/javamail#345]
I saved a draft message using GMail in the browser. But when I check the mail from java.mail. 
It seems that it does not contain the draft flag

```java
        // the folder is [Gmail]/Draft in Chinese
        Message[] messages = imapUtil.fetchMessageByIds("[Gmail]/草稿",
                new String[]{messageId}, "2018-10-18", "2018-10-18");

        for (Message m : messages) {
            MimeMessage msg = (MimeMessage) m;
            Constants.printIfDebug(msg.getSubject());
            Constants.printIfDebug(msg.getFlags().toString());
        }
```

the output is something like 

```
draft test
\Seen
```

Is it also a known issue that gmail does not set the draft flag properly?

**Comment by bshannon** [comment]
Yes, I just tried it as well and it appears to be a Gmail bug, please report it to Google.

**Comment by m00nlight** [comment]
@bshannon Thanks

**Comment by tysonzero** [comment]
Just ran into this. @m00nlight did you end up reporting it to google?

**Comment by m00nlight** [comment]
@tysonzero  Yeah, I reported it to google, but never get any response.
