### ISSUE TITLE
Expose the socket's local port in IMAPProtocol/Protocol

### ISSUE THREAD

**Issue by nvsnvikram** [eclipse-ee4j/javamail#356]
Socket is a private field and the only field unknown is local port. Would it be possible to add a method to expose the local port used by the imap client? It would greatly aid our tracing and logging.

**Comment by bshannon** [comment]
You need to know the local port number that the socket layer chose when connecting
to a remote server?  Do you not need the entire local address (Socket.getLocalSocketAddress)?

Note that it's a bit complicated for IMAP since there can be multiple connections associated with
a single Store - some in active use by the Store or Folders and some in the connection pool.

**Comment by nvsnvikram** [comment]
Local port is the only part we cannot figure out. Getting the entire local address will work as well. We need this api on Protocol class. From what I know, Protocol class handles only one connection at a time.

**Comment by bshannon** [comment]
How are you getting access to the Protocol instance?

**Comment by nvsnvikram** [comment]
We are creating a new IMAPProtocol instance to connect to a server.

**Comment by bshannon** [comment]
Are you subclassing the IMAP provider classes in order to do that?

**Comment by nvsnvikram** [comment]
Just plain IMAPProtocol and running commands on server. We don't use IMAP provider or Store or Folder classes.

**Comment by bshannon** [comment]
Oh.  I see.  Well, I'm sure you know that class was never designed for use that way.
Even if I made it work for you today, there's no guarantee that it would continue to
work in the future.

I'll consider your request, but I think you're far enough off from the intended use of
JavaMail that you might be better off forking the code to accomplish what you need.

Also, I'd be interested in understanding why the Store and Folder classes were not sufficient
for your needs.
