### ISSUE TITLE
Add tag with version number

### ISSUE THREAD

**Issue by salmanfs815** [eclipse-ee4j/javamail#357]
The tag on the latest (and only) release is 'initial-contribution'. It would be more helpful if the tag was '1.6.3' to clearly indicate the version.

**Comment by bshannon** [comment]
Once the release is final and the [Eclipse Release Review](https://projects.eclipse.org/projects/ee4j.javamail/reviews/1.6.3-release-review) is approved, I will tag it.
It is not yet final.

**Comment by bshannon** [comment]
FYI, the final version has been released and tagged.
