### ISSUE TITLE
Wrong text in link

### ISSUE THREAD

**Issue by FSchumacher** [eclipse-ee4j/javamail#362]
Copy&Paste error. Text in links should be `mail.imap.reusetagprefix` and not `mail.imap.compress.strategy`.

https://github.com/eclipse-ee4j/javamail/blob/a16edc5d6e65a102ff169caef1d7b21a3b416591/mail/src/main/java/com/sun/mail/imap/package.html#L912

**Comment by bshannon** [comment]
Thanks!
