### ISSUE TITLE
jakarta.mail: Compilation failure Version.java:[24,1] duplicate class: javax.mail.Version

### ISSUE THREAD

**Issue by guruhb** [eclipse-ee4j/javamail#368]
Compilation failure : 
mvn : 3.5.3 
JDK used 
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b07, mixed mode)
----

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/ghb/ade/github/eclipse-ee4j/javamail/mail/src/main/java/javax/mail/Version.java:[24,1] duplicate class: javax.mail.Version
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] 
[INFO] ------------------------< com.sun.mail:mailapi >------------------------
[INFO] Building JavaMail API (no providers) 1.6.4-SNAPSHOT               [3/23]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 

....
[INFO] Reactor Summary:
[INFO] 
[INFO] JavaMail API distribution 1.6.4-SNAPSHOT ........... SUCCESS [  0.885 s]
[INFO] JavaMail API ....................................... FAILURE [  2.070 s]
[INFO] JavaMail API (no providers) ........................ SUCCESS [  2.117 s]
[INFO] JavaMail API jar ................................... SUCCESS [  0.855 s]
[INFO] JavaMail API smtp provider ......................... SUCCESS [  0.454 s]
[INFO] JavaMail API imap provider ......................... SUCCESS [  0.806 s]
[INFO] JavaMail API Gmail IMAP provider ................... SUCCESS [  0.396 s]
[INFO] JavaMail API pop3 provider ......................... SUCCESS [  0.365 s]
[INFO] JavaMail API dsn support ........................... SUCCESS [  0.771 s]
[INFO] JavaMail API logging handler ....................... SUCCESS [  0.311 s]
[INFO] Android support for JavaMail ....................... SUCCESS [  0.203 s]
[INFO] JavaBeans Activation Framework fork for Android .... SUCCESS [  1.487 s]
[INFO] JavaMail API for Android ........................... SUCCESS [  1.838 s]
[INFO] JavaMail API mbox provider ......................... SUCCESS [ 25.129 s]
[INFO] JavaMail API demos ................................. SUCCESS [  0.413 s]
[INFO] JavaMail API demo client ........................... SUCCESS [  0.236 s]
[INFO] JavaMail API demo servlet .......................... SUCCESS [  0.174 s]
[INFO] JavaMail API demo taglib ........................... SUCCESS [  0.281 s]
[INFO] JavaMail API demo webapp ........................... SUCCESS [  0.403 s]
[INFO] JavaMail API logging demo .......................... SUCCESS [  0.201 s]
[INFO] JavaMail API demo Outlook message support .......... SUCCESS [  0.170 s]
[INFO] JavaMail API javadocs .............................. SUCCESS [01:36 min]
[INFO] JavaMail API publish project 1.6.4-SNAPSHOT ........ SUCCESS [  1.048 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:17 min
[INFO] Finished at: 2019-01-21T12:12:08+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project jakarta.mail: Compilation failure
[ERROR] /Users/ghb/ade/github/eclipse-ee4j/javamail/mail/src/main/java/javax/mail/Version.java:[24,1] duplicate class: javax.mail.Version
[ERROR] 
---

**Comment by guruhb** [comment]
Sorry, it could be a mistake 
Executed `ant` build and then `mvn clean package` which lead to the `duplicate class: javax.mail.Version` 

If i revert all untracked files and then execute `mvn clean package` : then this error is no more visible.

If this is expected behaviour (i.e not to mix and match with `ant` and `mvn` build) Please close this defect.

**Comment by bshannon** [comment]
Yes, please don't mix and match!

I haven't tried the ant build recently but the last time I tried it still worked.  Although with
some recent changes I won't be surprised if it has stopped working.
