### ISSUE TITLE
 javax.mail.internet.GetLocalAddressTest fails when host has no name

### ISSUE THREAD

**Issue by guruhb** [eclipse-ee4j/javamail#369]
Extra "[" occurs in the hostname (Only on Mac OS X while using only with network connected via Wifi)
------

expected:<Bob@[10.9.143.128]> but was:<Bob@[[10.9.143.128]]>

-------------------------------------------------------------------------------
Test set: javax.mail.internet.GetLocalAddressTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
testMailUserSpace(javax.mail.internet.GetLocalAddressTest)  Time elapsed: 0.004 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"NETWORK SERVICE"@[10.9.143.128]> but was:<"NETWORK SERVICE"@[[10.9.143.128]]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)

**Comment by bshannon** [comment]
The test wasn't handling the case where the local host has no name.
InetAddress returns the IP address in this case, and the test needed
to convert that into an address literal before using it in an email address
in the tests.
