### ISSUE TITLE
Add QUIT support on session rejection

### ISSUE THREAD

**Issue by diegosalvi** [eclipse-ee4j/javamail#372]
Hi,

this is an old issue that was left over before Oracle -> ESF switch (my bad, I didn't sign old contributor agreement).

Add quit on session rejection as per https://tools.ietf.org/html/rfc5321#section-3.1. New property quitOnSessionReject defaults keeping old behaviour but can set to true to respect RFC.

**Comment by bshannon** [comment]
Fixed by recent commit.
