### ISSUE TITLE
Update Scope Statement for Jakarta Mail Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/javamail#376]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by bshannon** [comment]
Proposed new scope statement:

Jakarta Mail provides a platform-independent and protocol-independent framework to build mail and messaging applications.  The Jakarta Mail project delivers a specification document and API.

The Jakarta Mail project also provides an implementation of internet standards and protocols such as MIME, IMAP, SMTP, and POP3, as well as extensions useful with popular devices, servers, and environments.

**Comment by waynebeaton** [comment]
AFAICT, the specification scope is this: "Jakarta Mail provides a platform-independent and protocol-independent framework to build mail and messaging applications. " Everything else is project scope.

**Comment by bshannon** [comment]
Right.  Assuming this project continues to cover both, the project scope needs to cover both.
Is there a separate place to declare the scope for the specification only?

**Comment by waynebeaton** [comment]
We've managed to conflate the specification and project scope statements. In my [blog post](https://waynebeaton.wordpress.com/2019/04/08/specification-scope-in-jakarta-ee/) on the topic, I suggested that the project scope is simply "The Jakarta Mail project maintains Jakarta Mail specification and related technical artifacts."

**Comment by waynebeaton** [comment]
I'm thinking that we need to change "provides" to "defines".

>Jakarta Mail **defines** a platform-independent and protocol-independent framework to build mail and messaging applications

**Comment by bshannon** [comment]
> We've managed to conflate the specification and project scope statements. In my blog post on the topic, I suggested that the project scope is simply "The Jakarta Mail project maintains Jakarta Mail specification and related technical artifacts."

Where would I go to find the specification scope?

"and related technical artifacts" is either far too limiting or incredibly open ended; which is intended?

**Comment by bshannon** [comment]
> I'm thinking that we need to change "provides" to "defines".

The specification "defines", the project "provides".

**Comment by waynebeaton** [comment]
We'll capture the project and specification scopes together (e.g. in the "Scope" field on the project's PMI page). I expect that an evolving pattern will be to include the specification scope in the specification document (the project scope would be out of place there).
