### ISSUE TITLE
Convert "Eclipse Project for JavaMail" into a specification project

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/javamail#380]
In order to prepare this project to engage in specification work, we need to convert it into a specification project as defined by the Eclipse Foundation Specification Process (EFSP). As part of this work, we will change the project name and the scope.

We'll use this issue to capture the work that needs to be done as part of this effort.

- [x] Resolve #377 
- [x] Resolve #376
- [ ] Successful complete a restructuring review
- [ ] Designate the project as a specification project of the Jakarta EE Working Group
- [ ] Change project name
- [ ] Change project scope

**Comment by waynebeaton** [comment]
A suggestion has been made that we should use this opportunity to refactor the project.

With this proposal, the "Jakarta Mail" project would become be a specification project that holds the specification document and TCK, and the existing javamail repository--which contains the API and an implementation--would be moved to a new project. To do this, we'll need a name for the new project.

What might be call a project that provides a compatible implementation of the Jakarta Mail specification?

**Comment by bshannon** [comment]
Since the specification is largely defined by the javadocs, which are intimately tied to the
implementation, I prefer that this project be converted to a specification project and the
API and implementation remain part of this project.

**Comment by bshannon** [comment]
@waynebeaton Is this complete?  Can we close this?
