### ISSUE TITLE
[Android] Cannot save attachment 

### ISSUE THREAD

**Issue by Sunghee2** [eclipse-ee4j/javamail#381]
```
 if(mailType.contains("multipart/mixed")) {
                MimeMultipart mimeMultipart = (MimeMultipart) body;
                Multipart multipart = (Multipart) body;
                try {
                    for (int i = 0; i < multipart.getCount(); i++) {
                        MimeBodyPart part = (MimeBodyPart) multipart.getBodyPart(i);
                        if (Part.ATTACHMENT.equalsIgnoreCase(part.getDisposition())) {
                            String filename = part.getFileName();
                            attachment_str.add(MimeUtility.decodeText(filename));

//                            part.saveFile(MimeUtility.decodeText(filename));
                            part.saveFile(filename);
```

I'm using an IMAP server.
I want to save the attachment, but there is an error in saveFile(). 
What should I do?
And when I use saveFile(), I wonder which path the attachment is stored in.

```
java.io.FileNotFoundException: =?UTF-8?B?bGlua3MuY3N2?= (Read-only file system)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:287)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at javax.mail.internet.MimeBodyPart.saveFile(MimeBodyPart.java:830)
    at javax.mail.internet.MimeBodyPart.saveFile(MimeBodyPart.java:860)
```

**Comment by bshannon** [comment]
The attachment is stored in the file whose name you provide.  If you give it a
relative path name, it will be relative to the current directory of the application.

You can see from the exception that the file name is encoded; you've commented
out the line that uses the decoded file name.  See the [JavaMail FAQ](https://javaee.github.io/javamail/FAQ#encodefilename) for more
information on encoding and decoding file names.

Note also that the file name included in a mail message is not trustworthy.
You should always validate that the file is not going to overwrite an existing
file or be created in a directory that would cause security problems.

One approach is to construct a File object with the (decoded) file name,
extract the simple name of the file (without any directories), and use that
to construct a new File object located in a specific directory that you control.
Use that File object with the [saveFile method](https://javaee.github.io/javamail/docs/api/javax/mail/internet/MimeBodyPart.html#saveFile-java.io.File-).
